// Authentication
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const LOGOUT = 'LOGOUT';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const GET_PRIMARY_CATEGORIES_SUCCESS = 'GET_PRIMARY_CATEGORIES_SUCCESS';
export const GET_PRIMARY_CATEGORIES_FAIL = 'GET_PRIMARY_CATEGORIES_FAIL';
export const GET_CATEGORY_COURSES_SUCCESS = 'GET_CATEGORY_COURSES_SUCCESS';
export const GET_CATEGORY_COURSES_FAIL = 'GET_CATEGORY_COURSES_FAIL';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_FAIL = 'GET_PRODUCT_CATEGORIES_FAIL';
export const GET_GAMES_CATEGORIES_SUCCESS = 'GET_GAMES_CATEGORIES_SUCCESS';
export const GET_GAMES_CATEGORIES_FAIL = 'GET_GAMES_CATEGORIES_FAIL';
export const GET_VIDEO_CATEGORIES_SUCCESS = 'GET_VIDEO_CATEGORIES_SUCCESS';
export const GET_VIDEO_CATEGORIES_FAIL = 'GET_VIDEO_CATEGORIES_FAIL';

// Products
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCTS_BY_ARRIVAL_SUCCESS = 'GET_PRODUCTS_BY_ARRIVAL_SUCCESS';
export const GET_PRODUCTS_BY_ARRIVAL_FAIL = 'GET_PRODUCTS_BY_ARRIVAL_FAIL';
export const GET_PRODUCTS_BY_SOLD_SUCCESS = 'GET_PRODUCTS_BY_SOLD_SUCCESS';
export const GET_PRODUCTS_BY_SOLD_FAIL = 'GET_PRODUCTS_BY_SOLD_FAIL';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_PRODUCTS_FROM_VENDOR_SUCCESS = 'GET_PRODUCTS_FROM_VENDOR_SUCCESS';
export const GET_PRODUCTS_FROM_VENDOR_FAIL = 'GET_PRODUCTS_FROM_VENDOR_FAIL';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';
export const RELATED_PRODUCTS_SUCCESS = 'RELATED_PRODUCTS_SUCCESS';
export const RELATED_PRODUCTS_FAIL = 'RELATED_PRODUCTS_FAIL';
export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS';
export const FILTER_PRODUCTS_FAIL = 'FILTER_PRODUCTS_FAIL';


// CategoriesClassroom
export const GET_CATEGORIES_CLASSROOM_SUCCESS = 'GET_CATEGORIES_CLASSROOM_SUCCESS';
export const GET_CATEGORIES_CLASSROOM_FAIL = 'GET_CATEGORIES_CLASSROOM_FAIL';
export const GET_COURSESCLASSROOM_SUCCESS = 'GET_COURSESCLASSROOM_SUCCESS';
export const GET_COURSESCLASSROOM_FAIL = 'GET_COURSESCLASSROOM_FAIL';
export const GET_COURSE_CLASSROOM_DETAILS_SUCCESS = 'GET_COURSE_CLASSROOM_DETAILS_SUCCESS';
export const GET_COURSE_CLASSROOM_DETAILS_FAIL = 'GET_COURSE_CLASSROOM_DETAILS_FAIL';
export const GET_MODULE_DETAILS_SUCCESS = 'GET_MODULE_DETAILS_SUCCESS';
export const GET_MODULE_DETAILS_FAIL = 'GET_MODULE_DETAILS_FAIL';
export const GET_PAGE_DETAILS_SUCCESS = 'GET_PAGE_DETAILS_SUCCESS';
export const GET_PAGE_DETAILS_FAIL = 'GET_PAGE_DETAILS_FAIL';
export const GET_QUIZ_DETAILS_SUCCESS = 'GET_QUIZ_DETAILS_SUCCESS';
export const GET_QUIZ_DETAILS_FAIL = 'GET_QUIZ_DETAILS_FAIL';
export const GET_ASSIGNMENT_DETAILS_SUCCESS = 'GET_ASSIGNMENT_DETAILS_SUCCESS';
export const GET_ASSIGNMENT_DETAILS_FAIL = 'GET_ASSIGNMENT_DETAILS_FAIL';
export const GET_ATTEMPT_DETAILS_SUCCESS = 'GET_ATTEMPT_DETAILS_SUCCESS';
export const GET_ATTEMPT_DETAILS_FAIL = 'GET_ATTEMPT_DETAILS_FAIL';
export const GET_MY_SUBMISSIONS_SUCCESS = 'GET_MY_SUBMISSIONS_SUCCESS';
export const GET_MY_SUBMISSIONS_FAIL = 'GET_MY_SUBMISSIONS_FAIL';
export const GET_STUDENT_SUBMISSIONS_SUCCESS = 'GET_STUDENT_SUBMISSIONS_SUCCESS';
export const GET_STUDENT_SUBMISSIONS_FAIL = 'GET_STUDENT_SUBMISSIONS_FAIL';
export const GET_QUIZ_ATTEMPTS_SUCCESS = 'GET_QUIZ_ATTEMPTS_SUCCESS';
export const GET_QUIZ_ATTEMPTS_FAIL = 'GET_QUIZ_ATTEMPTS_FAIL';
export const GET_GRADES_SUCCESS = 'GET_GRADES_SUCCESS';
export const GET_GRADES_FAIL = 'GET_GRADES_FAIL';
export const GET_CATEGORY_DETAILS_SUCCESS = 'GET_CATEGORY_DETAILS_SUCCESS';
export const GET_CATEGORY_DETAILS_FAIL = 'GET_CATEGORY_DETAILS_FAIL';
export const GET_PAGE_COMPLETIONS_SUCCESS = 'GET_PAGE_COMPLETIONS_SUCCESS';
export const GET_PAGE_COMPLETIONS_FAIL = 'GET_PAGE_COMPLETIONS_FAIL';
export const GET_PAGES_COMPLETIONS_SUCCESS = 'GET_PAGES_COMPLETIONS_SUCCESS';
export const GET_PAGES_COMPLETIONS_FAIL = 'GET_PAGES_COMPLETIONS_FAIL';
export const GET_ASSIGNMENT_COMPLETIONS_SUCCESS = 'GET_ASSIGNMENT_COMPLETIONS_SUCCESS';
export const GET_ASSIGNMENT_COMPLETIONS_FAIL = 'GET_ASSIGNMENT_COMPLETIONS_FAIL';
export const GET_QUIZ_COMPLETIONS_SUCCESS = 'GET_QUIZ_COMPLETIONS_SUCCESS';
export const GET_QUIZ_COMPLETIONS_FAIL = 'GET_QUIZ_COMPLETIONS_FAIL';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL';
export const GET_QUESTION_DETAILS_SUCCESS = 'GET_QUESTION_DETAILS_SUCCESS';
export const GET_QUESTION_DETAILS_FAIL = 'GET_QUESTION_DETAILS_FAIL';
export const GET_QUESTION_ANSWERS_SUCCESS = 'GET_QUESTION_ANSWERS_SUCCESS';
export const GET_QUESTION_ANSWERS_FAIL = 'GET_QUESTION_ANSWERS_FAIL';
export const GET_GRADE_DETAILS_SUCCESS = 'GET_GRADE_DETAILS_SUCCESS';
export const GET_GRADE_DETAILS_FAIL = 'GET_GRADE_DETAILS_FAIL';
export const GET_CLASSROOM_MODULES_SUCCESS = 'GET_CLASSROOM_MODULES_SUCCESS';
export const GET_CLASSROOM_MODULES_FAIL = 'GET_CLASSROOM_MODULES_FAIL';

// Enrolled Courses
export const GET_ENROLLED_COURSES_SUCCESS = 'GET_ENROLLED_COURSES_SUCCESS';
export const GET_ENROLLED_COURSES_FAIL = 'GET_ENROLLED_COURSES_FAIL';

// DemoPage
export const GET_DEMOPAGE_SUCCESS = 'GET_DEMOPAGE_SUCCESS';
export const GET_DEMOPAGE_FAIL = 'GET_DEMOPAGE_FAIL';

// Get prices
export const GET_PRICES_SUCCESS = 'GET_PRICES_SUCCESS';
export const GET_PRICES_FAIL = 'GET_PRICES_FAIL';

// Blog
export const GET_BLOG_CATEGORIES_SUCCESS = 'GET_BLOG_CATEGORIES_SUCCESS';
export const GET_BLOG_CATEGORIES_FAIL = 'GET_BLOG_CATEGORIES_FAIL';
export const GET_BLOG_LIST_SUCCESS = 'GET_BLOG_LIST_SUCCESS';
export const GET_BLOG_LIST_FAIL = 'GET_BLOG_LIST_FAIL';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL';
export const GET_BLOG_FEATURED_LIST_SUCCESS = 'GET_BLOG_FEATURED_LIST_SUCCESS';
export const GET_BLOG_FEATURED_LIST_FAIL = 'GET_BLOG_FEATURED_LIST_FAIL';

// Members from Team
export const GET_LEADERS_SUCCESS = 'GET_LEADERS_SUCCESS';
export const GET_LEADERS_FAIL = 'GET_LEADERS_FAIL';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_FAIL = 'GET_MEMBERS_FAIL';

// Topics
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAIL = 'GET_TOPICS_FAIL';
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS';
export const GET_FAQS_FAIL = 'GET_FAQS_FAIL';

// Courses
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';
export const GET_COURSES_BY_ARRIVAL_SUCCESS = 'GET_COURSES_BY_ARRIVAL_SUCCESS';
export const GET_COURSES_BY_ARRIVAL_FAIL = 'GET_COURSES_BY_ARRIVAL_FAIL';
export const GET_COURSES_BY_SOLD_SUCCESS = 'GET_COURSES_BY_SOLD_SUCCESS';
export const GET_COURSES_BY_SOLD_FAIL = 'GET_COURSES_BY_SOLD_FAIL';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';
export const GET_COURSE_STUDY_SUCCESS = 'GET_COURSE_STUDY_SUCCESS';
export const GET_COURSE_STUDY_FAIL = 'GET_COURSE_STUDY_FAIL';
export const SEARCH_COURSES_SUCCESS = 'SEARCH_COURSES_SUCCESS';
export const SEARCH_COURSES_FAIL = 'SEARCH_COURSES_FAIL';
export const RELATED_COURSES_SUCCESS = 'RELATED_COURSES_SUCCESS';
export const RELATED_COURSES_FAIL = 'RELATED_COURSES_FAIL';
export const FILTER_COURSES_SUCCESS = 'FILTER_COURSES_SUCCESS';
export const FILTER_COURSES_FAIL = 'FILTER_COURSES_FAIL';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAIL = 'GET_RESOURCES_FAIL';
export const GET_COURSE_QUESTIONS_SUCCESS = 'GET_COURSE_QUESTIONS_SUCCESS';
export const GET_COURSE_QUESTIONS_FAIL = 'GET_COURSE_QUESTIONS_FAIL';


// Reviews
export const GET_COURSE_REVIEWS_SUCCESS = 'GET_COURSE_REVIEWS_SUCCESS';
export const GET_COURSE_REVIEWS_FAIL = 'GET_COURSE_REVIEWS_FAIL';
export const GET_COURSE_REVIEW_SUCCESS = 'GET_COURSE_REVIEW_SUCCESS';
export const GET_COURSE_REVIEW_FAIL = 'GET_COURSE_REVIEW_FAIL';
export const CREATE_COURSE_REVIEW_SUCCESS = 'CREATE_COURSE_REVIEW_SUCCESS';
export const CREATE_COURSE_REVIEW_FAIL = 'CREATE_COURSE_REVIEW_FAIL';
export const UPDATE_COURSE_REVIEW_SUCCESS = 'UPDATE_COURSE_REVIEW_SUCCESS';
export const UPDATE_COURSE_REVIEW_FAIL = 'UPDATE_COURSE_REVIEW_FAIL';
export const DELETE_COURSE_REVIEW_SUCCESS = 'DELETE_COURSE_REVIEW_SUCCESS';
export const DELETE_COURSE_REVIEW_FAIL = 'DELETE_COURSE_REVIEW_FAIL';
export const FILTER_COURSE_REVIEWS_SUCCESS = 'FILTER_COURSE_REVIEWS_SUCCESS';
export const FILTER_COURSE_REVIEWS_FAIL = 'FILTER_COURSE_REVIEWS_FAIL';

export const GET_VIDEO_REVIEWS_SUCCESS = 'GET_VIDEO_REVIEWS_SUCCESS';
export const GET_VIDEO_REVIEWS_FAIL = 'GET_VIDEO_REVIEWS_FAIL';
export const GET_VIDEO_REVIEW_SUCCESS = 'GET_VIDEO_REVIEW_SUCCESS';
export const GET_VIDEO_REVIEW_FAIL = 'GET_VIDEO_REVIEW_FAIL';
export const CREATE_VIDEO_REVIEW_SUCCESS = 'CREATE_VIDEO_REVIEW_SUCCESS';
export const CREATE_VIDEO_REVIEW_FAIL = 'CREATE_VIDEO_REVIEW_FAIL';
export const UPDATE_VIDEO_REVIEW_SUCCESS = 'UPDATE_VIDEO_REVIEW_SUCCESS';
export const UPDATE_VIDEO_REVIEW_FAIL = 'UPDATE_VIDEO_REVIEW_FAIL';
export const DELETE_VIDEO_REVIEW_SUCCESS = 'DELETE_VIDEO_REVIEW_SUCCESS';
export const DELETE_VIDEO_REVIEW_FAIL = 'DELETE_VIDEO_REVIEW_FAIL';
export const FILTER_VIDEO_REVIEWS_SUCCESS = 'FILTER_VIDEO_REVIEWS_SUCCESS';
export const FILTER_VIDEO_REVIEWS_FAIL = 'FILTER_VIDEO_REVIEWS_FAIL';

export const GET_GAME_REVIEWS_SUCCESS = 'GET_GAME_REVIEWS_SUCCESS';
export const GET_GAME_REVIEWS_FAIL = 'GET_GAME_REVIEWS_FAIL';
export const GET_GAME_REVIEW_SUCCESS = 'GET_GAME_REVIEW_SUCCESS';
export const GET_GAME_REVIEW_FAIL = 'GET_GAME_REVIEW_FAIL';
export const CREATE_GAME_REVIEW_SUCCESS = 'CREATE_GAME_REVIEW_SUCCESS';
export const CREATE_GAME_REVIEW_FAIL = 'CREATE_GAME_REVIEW_FAIL';
export const UPDATE_GAME_REVIEW_SUCCESS = 'UPDATE_GAME_REVIEW_SUCCESS';
export const UPDATE_GAME_REVIEW_FAIL = 'UPDATE_GAME_REVIEW_FAIL';
export const DELETE_GAME_REVIEW_SUCCESS = 'DELETE_GAME_REVIEW_SUCCESS';
export const DELETE_GAME_REVIEW_FAIL = 'DELETE_GAME_REVIEW_FAIL';
export const FILTER_GAME_REVIEWS_SUCCESS = 'FILTER_GAME_REVIEWS_SUCCESS';
export const FILTER_GAME_REVIEWS_FAIL = 'FILTER_GAME_REVIEWS_FAIL';



export const GET_PRODUCT_REVIEWS_SUCCESS = 'GET_PRODUCT_REVIEWS_SUCCESS';
export const GET_PRODUCT_REVIEWS_FAIL = 'GET_PRODUCT_REVIEWS_FAIL';
export const GET_PRODUCT_REVIEW_SUCCESS = 'GET_PRODUCT_REVIEW_SUCCESS';
export const GET_PRODUCT_REVIEW_FAIL = 'GET_PRODUCT_REVIEW_FAIL';
export const CREATE_PRODUCT_REVIEW_SUCCESS = 'CREATE_PRODUCT_REVIEW_SUCCESS';
export const CREATE_PRODUCT_REVIEW_FAIL = 'CREATE_PRODUCT_REVIEW_FAIL';
export const UPDATE_PRODUCT_REVIEW_SUCCESS = 'UPDATE_PRODUCT_REVIEW_SUCCESS';
export const UPDATE_PRODUCT_REVIEW_FAIL = 'UPDATE_PRODUCT_REVIEW_FAIL';
export const DELETE_PRODUCT_REVIEW_SUCCESS = 'DELETE_PRODUCT_REVIEW_SUCCESS';
export const DELETE_PRODUCT_REVIEW_FAIL = 'DELETE_PRODUCT_REVIEW_FAIL';
export const FILTER_PRODUCT_REVIEWS_SUCCESS = 'FILTER_PRODUCT_REVIEWS_SUCCESS';
export const FILTER_PRODUCT_REVIEWS_FAIL = 'FILTER_PRODUCT_REVIEWS_FAIL';
export const GET_USER_PRODUCTS_SUCCESS = 'GET_USER_PRODUCTS_SUCCESS';
export const GET_USER_PRODUCTS_FAIL = 'GET_USER_PRODUCTS_FAIL';
export const GET_USER_PURCHASED_PRODUCTS_SUCCESS = 'GET_USER_PURCHASED_PRODUCTS_SUCCESS';
export const GET_USER_PURCHASED_PRODUCTS_FAIL = 'GET_USER_PURCHASED_PRODUCTS_FAIL';


// Teacher Courses
export const GET_MY_COURSES_SUCCESS = 'GET_MY_COURSES_SUCCESS';
export const GET_MY_COURSES_FAIL = 'GET_MY_COURSES_FAIL';
export const GET_COURSE_SECTION_SUCCESS = 'GET_COURSE_SECTION_SUCCESS';
export const GET_COURSE_SECTION_FAIL = 'GET_COURSE_SECTION_FAIL';
export const GET_RESOURCES_LIST_SUCCESS = 'GET_RESOURCES_LIST_SUCCESS';
export const GET_RESOURCES_LIST_FAIL = 'GET_RESOURCES_LIST_FAIL';
export const GET_EPISODE_SUCCESS = 'GET_EPISODE_SUCCESS';
export const GET_EPISODE_FAIL = 'GET_EPISODE_FAIL';
export const CREATE_VENDOR_ACCOUNT_SUCCESS = 'CREATE_VENDOR_ACCOUNT_SUCCESS';
export const CREATE_VENDOR_ACCOUNT_FAIL = 'CREATE_VENDOR_ACCOUNT_FAIL';
export const RETRIEVE_VENDOR_ACCOUNT_SUCCESS = 'RETRIEVE_VENDOR_ACCOUNT_SUCCESS';
export const RETRIEVE_VENDOR_ACCOUNT_FAIL = 'RETRIEVE_VENDOR_ACCOUNT_FAIL';


export const GET_REQUISITES_SUCCESS = 'GET_REQUISITES_SUCCESS';
export const GET_REQUISITES_FAIL = 'GET_REQUISITES_FAIL';
export const GET_WHATLEARNT_SUCCESS = 'GET_WHATLEARNT_SUCCESS';
export const GET_WHATLEARNT_FAIL = 'GET_WHATLEARNT_FAIL';
export const GET_SECTIONS_SUCCESS = 'GET_SECTIONS_SUCCESS';
export const GET_SECTIONS_FAIL = 'GET_SECTIONS_FAIL';
export const GET_PAID_SECTIONS_SUCCESS = 'GET_PAID_SECTIONS_SUCCESS';
export const GET_PAID_SECTIONS_FAIL = 'GET_PAID_SECTIONS_FAIL';
export const GET_COURSE_PRICES_SUCCESS = 'GET_COURSE_PRICES_SUCCESS';
export const GET_COURSE_PRICES_FAIL = 'GET_COURSE_PRICES_FAIL';
export const GET_COURSE_AUTHOR_SUCCESS = 'GET_COURSE_AUTHOR_SUCCESS';
export const GET_COURSE_AUTHOR_FAIL = 'GET_COURSE_AUTHOR_FAIL';
export const GET_COURSE_DETAILS_SUCCESS = 'GET_COURSE_DETAILS_SUCCESS';
export const GET_COURSE_DETAILS_FAIL = 'GET_COURSE_DETAILS_FAIL';
export const GET_USER_COURSES_SUCCESS = 'GET_USER_COURSES_SUCCESS';
export const GET_USER_COURSES_FAIL = 'GET_USER_COURSES_FAIL';
export const GET_COURSES_LIBRARY_SUCCESS = 'GET_COURSES_LIBRARY_SUCCESS';
export const GET_COURSES_LIBRARY_FAIL = 'GET_COURSES_LIBRARY_FAIL';
export const GET_PAID_COURSES_LIBRARY_SUCCESS = 'GET_PAID_COURSES_LIBRARY_SUCCESS';
export const GET_PAID_COURSES_LIBRARY_FAIL = 'GET_PAID_COURSES_LIBRARY_FAIL';


export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAIL = 'SEARCH_PRODUCT_FAIL';


export const GET_DISCOUNT_SUCCESS = 'GET_DISCOUNT_SUCCESS';
export const GET_DISCOUNT_FAIL = 'GET_DISCOUNT_FAIL';


// Local Cart
export const ADD_ITEM = 'ADD_ITEM';
export const GET_TOTAL = 'GET_TOTAL';
export const GET_ITEM_TOTAL = 'GET_ITEM_TOTAL';
export const GET_ITEMS = 'GET_ITEMS';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const EMPTY_CART = 'EMPTY_CART';

// Database Cart
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const GET_TOTAL_SUCCESS = 'GET_TOTAL_SUCCESS';
export const GET_TOTAL_FAIL = 'GET_TOTAL_FAIL';
export const GET_ITEM_TOTAL_SUCCESS = 'GET_ITEM_TOTAL_SUCCESS';
export const GET_ITEM_TOTAL_FAIL = 'GET_ITEM_TOTAL_FAIL';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL';
export const SYNCH_CART_SUCCESS = 'SYNCH_CART_SUCCESS';
export const SYNCH_CART_FAIL = 'SYNCH_CART_FAIL';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL';

// Shipping
export const GET_SHIPPING_OPTIONS_SUCCESS = 'GET_SHIPPING_OPTIONS_SUCCESS';
export const GET_SHIPPING_OPTIONS_FAIL = 'GET_SHIPPING_OPTIONS_FAIL';

// Coupons
export const GET_COUPON_SUCCESS = 'GET_COUPON_SUCCESS';
export const GET_COUPON_FAIL = 'GET_COUPON_FAIL';

// Orders
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';
export const GET_ORDER_ITEMS_SUCCESS = 'GET_ORDER_ITEMS_SUCCESS';
export const GET_ORDER_ITEMS_FAIL = 'GET_ORDER_ITEMS_FAIL';
export const GET_ORDER_ITEM_SUCCESS = 'GET_ORDER_ITEM_SUCCESS';
export const GET_ORDER_ITEM_FAIL = 'GET_ORDER_ITEM_FAIL';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const CREATE_GAME_ORDER_SUCCESS = 'CREATE_GAME_ORDER_SUCCESS'
export const CREATE_GAME_ORDER_FAIL = 'CREATE_GAME_ORDER_FAIL'
export const SET_ORDERS_LOADING = 'SET_ORDERS_LOADING'
export const REMOVE_ORDERS_LOADING = 'REMOVE_ORDERS_LOADING'

//Payments
export const GET_PAYMENT_TOTAL_SUCCESS = 'GET_PAYMENT_TOTAL_SUCCESS';
export const GET_PAYMENT_TOTAL_FAIL = 'GET_PAYMENT_TOTAL_FAIL';
export const LOAD_BT_TOKEN_SUCCESS = 'LOAD_BT_TOKEN_SUCCESS';
export const LOAD_BT_TOKEN_FAIL = 'LOAD_BT_TOKEN_FAIL';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';
export const RESET_PAYMENT_INFO = 'RESET_PAYMENT_INFO';
export const SET_PAYMENT_LOADING = 'SET_PAYMENT_LOADING';
export const REMOVE_PAYMENT_LOADING = 'REMOVE_PAYMENT_LOADING';
export const CREATE_STRIPE_PAYMENT_INTENT_SUCCESS = 'CREATE_STRIPE_PAYMENT_INTENT_SUCCESS'
export const CREATE_STRIPE_PAYMENT_INTENT_FAIL= 'CREATE_STRIPE_PAYMENT_INTET_FAIL'
export const CREATE_STRIPE_GAME_PAYMENT_INTENT_SUCCESS = 'CREATE_STRIPE_GAME_PAYMENT_INTENT_SUCCESS'
export const CREATE_STRIPE_GAME_PAYMENT_INTENT_FAIL= 'CREATE_STRIPE_GAME_PAYMENT_INTET_FAIL'
export const MADE_STRIPE_PAYMENT = 'MADE_STRIPE_PAYMENT'

// Wishlist
export const GET_WISHLIST_ITEMS_SUCCESS = 'GET_WISHLIST_ITEMS_SUCCESS';
export const GET_WISHLIST_ITEMS_FAIL = 'GET_WISHLIST_ITEMS_FAIL';
export const ADD_WISHLIST_ITEM_SUCCESS = 'ADD_WISHLIST_ITEM_SUCCESS';
export const ADD_WISHLIST_ITEM_FAIL = 'ADD_WISHLIST_ITEM_FAIL';
export const GET_WISHLIST_ITEM_TOTAL_SUCCESS = 'GET_WISHLIST_ITEM_TOTAL_SUCCESS';
export const GET_WISHLIST_ITEM_TOTAL_FAIL = 'GET_WISHLIST_ITEM_TOTAL_FAIL';
export const REMOVE_WISHLIST_ITEM_SUCCESS = 'REMOVE_WISHLIST_ITEM_SUCCESS';
export const REMOVE_WISHLIST_ITEM_FAIL = 'REMOVE_WISHLIST_ITEM_FAIL';
export const CREATE_WISHLIST_SUCCESS = 'CREATE_WISHLIST_SUCCESS';
export const CREATE_WISHLIST_FAIL = 'CREATE_WISHLIST_FAIL';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';


// SOCIAL //

// Post
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
export const GET_BOOKMARKS_FAIL = 'GET_BOOKMARKS_FAIL';
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS';
export const GET_POST_DETAILS_FAIL = 'GET_POST_DETAILS_FAIL';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_FAIL = 'GET_USER_POSTS_FAIL';
export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS';
export const GET_POST_COMMENTS_FAIL = 'GET_POST_COMMENTS_FAIL';



// GAMES // 
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL';
export const GET_GAME_DETAILS_SUCCESS = 'GET_GAME_DETAILS_SUCCESS';
export const GET_GAME_DETAILS_FAIL = 'GET_GAME_DETAILS_FAIL';
export const GET_GAMES_BY_ARRIVAL_SUCCESS = 'GET_GAMES_BY_ARRIVAL_SUCCESS';
export const GET_GAMES_BY_ARRIVAL_FAIL = 'GET_GAMES_BY_ARRIVAL_FAIL';
export const GET_GAMES_BY_SOLD_SUCCESS = 'GET_GAMES_BY_SOLD_SUCCESS';
export const GET_GAMES_BY_SOLD_FAIL = 'GET_GAMES_BY_SOLD_FAIL';
export const GET_GAMES_BY_RATING_SUCCESS = 'GET_GAMES_BY_RATING_SUCCESS';
export const GET_GAMES_BY_RATING_FAIL = 'GET_GAMES_BY_RATING_FAIL';
export const SEARCH_GAMES_SUCCESS = 'SEARCH_GAMES_SUCCESS';
export const SEARCH_GAMES_FAIL = 'SEARCH_GAMES_FAIL';
export const RELATED_GAMES_SUCCESS = 'RELATED_GAMES_SUCCESS';
export const RELATED_GAMES_FAIL = 'RELATED_GAMES_FAIL';
export const FILTER_GAMES_SUCCESS = 'FILTER_GAMES_SUCCESS';
export const FILTER_GAMES_FAIL = 'FILTER_GAMES_FAIL';
export const GET_USER_GAMES_SUCCESS = 'GET_USER_GAMES_SUCCESS';
export const GET_USER_GAMES_FAIL = 'GET_USER_GAMES_FAIL';
export const GET_USER_GAMES_PUBLISHED_SUCCESS = 'GET_USER_GAMES_PUBLISHED_SUCCESS';
export const GET_USER_GAMES_PUBLISHED_FAIL = 'GET_USER_GAMES_PUBLISHED_FAIL';
export const CREATE_GAMESLIBRARY_SUCCESS = 'CREATE_GAMESLIBRARY_SUCCESS';
export const CREATE_GAMESLIBRARY_FAIL = 'CREATE_GAMESLIBRARY_FAIL';
export const GET_GAMESLIBRARY_SUCCESS = 'GET_GAMESLIBRARY_SUCCESS';
export const GET_GAMESLIBRARY_FAIL = 'GET_GAMESLIBRARY_FAIL';


export const CREATE_DIGITAL_PRODUCTS_LIBRARY_SUCCESS = 'CREATE_DIGITAL_PRODUCTS_LIBRARY_SUCCESS';
export const CREATE_DIGITAL_PRODUCTS_LIBRARY_FAIL = 'CREATE_DIGITAL_PRODUCTS_LIBRARY_FAIL';
export const GET_DIGITAL_PRODUCTS_SUCCESS = 'GET_DIGITAL_PRODUCTS_SUCCESS';
export const GET_DIGITAL_PRODUCTS_FAIL = 'GET_DIGITAL_PRODUCTS_FAIL';
export const GET_DIGITAL_PRODUCTS_BY_ARRIVAL_SUCCESS = 'GET_DIGITAL_PRODUCTS_BY_ARRIVAL_SUCCESS';
export const GET_DIGITAL_PRODUCTS_BY_ARRIVAL_FAIL = 'GET_DIGITAL_PRODUCTS_BY_ARRIVAL_FAIL';
export const GET_DIGITAL_PRODUCTS_BY_SOLD_SUCCESS = 'GET_DIGITAL_PRODUCTS_BY_SOLD_SUCCESS';
export const GET_DIGITAL_PRODUCTS_BY_SOLD_FAIL = 'GET_DIGITAL_PRODUCTS_BY_SOLD_FAIL';
export const GET_DIGITAL_PRODUCT_SUCCESS = 'GET_DIGITAL_PRODUCT_SUCCESS';
export const GET_DIGITAL_PRODUCT_FAIL = 'GET_DIGITAL_PRODUCT_FAIL';
export const GET_DIGITAL_PRODUCT_STUDY_SUCCESS = 'GET_DIGITAL_PRODUCT_STUDY_SUCCESS';
export const GET_DIGITAL_PRODUCT_STUDY_FAIL = 'GET_DIGITAL_PRODUCT_STUDY_FAIL';
export const SEARCH_DIGITAL_PRODUCTS_SUCCESS = 'SEARCH_DIGITAL_PRODUCTS_SUCCESS';
export const SEARCH_DIGITAL_PRODUCTS_FAIL = 'SEARCH_DIGITAL_PRODUCTS_FAIL';
export const RELATED_DIGITAL_PRODUCTS_SUCCESS = 'RELATED_DIGITAL_PRODUCTS_SUCCESS';
export const RELATED_DIGITAL_PRODUCTS_FAIL = 'RELATED_DIGITAL_PRODUCTS_FAIL';
export const FILTER_DIGITAL_PRODUCTS_SUCCESS = 'FILTER_DIGITAL_PRODUCTS_SUCCESS';
export const FILTER_DIGITAL_PRODUCTS_FAIL = 'FILTER_DIGITAL_PRODUCTS_FAIL';
export const GET_USER_DIGITAL_PRODUCTS_SUCCESS = 'GET_USER_DIGITAL_PRODUCTS_SUCCESS';
export const GET_USER_DIGITAL_PRODUCTS_FAIL = 'GET_USER_DIGITAL_PRODUCTS_FAIL';


export const CREATE_MOVIE_STUDIO_SUCCESS = 'CREATE_MOVIE_STUDIO_SUCCESS';
export const CREATE_MOVIE_STUDIO_FAIL = 'CREATE_MOVIE_STUDIO_FAIL';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';
export const GET_MOVIES_BY_ARRIVAL_SUCCESS = 'GET_MOVIES_BY_ARRIVAL_SUCCESS';
export const GET_MOVIES_BY_ARRIVAL_FAIL = 'GET_MOVIES_BY_ARRIVAL_FAIL';
export const GET_MOVIES_BY_SOLD_SUCCESS = 'GET_MOVIES_BY_SOLD_SUCCESS';
export const GET_MOVIES_BY_SOLD_FAIL = 'GET_MOVIES_BY_SOLD_FAIL';
export const GET_MOVIES_BY_RATING_SUCCESS = 'GET_MOVIES_BY_RATING_SUCCESS';
export const GET_MOVIES_BY_RATING_FAIL = 'GET_MOVIES_BY_RATING_FAIL';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';
export const RELATED_MOVIES_SUCCESS = 'RELATED_MOVIES_SUCCESS';
export const RELATED_MOVIES_FAIL = 'RELATED_MOVIES_FAIL';
export const FILTER_MOVIES_SUCCESS = 'FILTER_MOVIES_SUCCESS';
export const FILTER_MOVIES_FAIL = 'FILTER_MOVIES_FAIL';
export const GET_USER_MOVIES_SUCCESS = 'GET_USER_MOVIES_SUCCESS';
export const GET_USER_MOVIES_FAIL = 'GET_USER_MOVIES_FAIL';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';


export const CREATE_MUSIC_PLAYLIST_SUCCESS = 'CREATE_MUSIC_PLAYLIST_SUCCESS';
export const CREATE_MUSIC_PLAYLIST_FAIL = 'CREATE_MUSIC_PLAYLIST_FAIL';
export const CREATE_ALBUM_LIST_SUCCESS = 'CREATE_ALBUM_LIST_SUCCESS';
export const CREATE_ALBUM_LIST_FAIL = 'CREATE_ALBUM_LIST_FAIL';
export const CREATE_TRACK_LIST_SUCCESS = 'CREATE_TRACK_LIST_SUCCESS';
export const CREATE_TRACK_LIST_FAIL = 'CREATE_TRACK_LIST_FAIL';
export const CREATE_ARTIST_LIST_SUCCESS = 'CREATE_ARTIST_LIST_SUCCESS';
export const CREATE_ARTIST_LIST_FAIL = 'CREATE_ARTIST_LIST_FAIL';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONGS_FAIL = 'GET_SONGS_FAIL';
export const GET_SONGS_BY_ARRIVAL_SUCCESS = 'GET_SONGS_BY_ARRIVAL_SUCCESS';
export const GET_SONGS_BY_ARRIVAL_FAIL = 'GET_SONGS_BY_ARRIVAL_FAIL';
export const GET_SONGS_BY_SOLD_SUCCESS = 'GET_SONGS_BY_SOLD_SUCCESS';
export const GET_SONGS_BY_SOLD_FAIL = 'GET_SONGS_BY_SOLD_FAIL';
export const GET_SONGS_BY_RATING_SUCCESS = 'GET_SONGS_BY_RATING_SUCCESS';
export const GET_SONGS_BY_RATING_FAIL = 'GET_SONGS_BY_RATING_FAIL';
export const SEARCH_SONGS_SUCCESS = 'SEARCH_SONGS_SUCCESS';
export const SEARCH_SONGS_FAIL = 'SEARCH_SONGS_FAIL';
export const RELATED_SONGS_SUCCESS = 'RELATED_SONGS_SUCCESS';
export const RELATED_SONGS_FAIL = 'RELATED_SONGS_FAIL';
export const FILTER_SONGS_SUCCESS = 'FILTER_SONGS_SUCCESS';
export const FILTER_SONGS_FAIL = 'FILTER_SONGS_FAIL';
export const GET_USER_SONGS_SUCCESS = 'GET_USER_SONGS_SUCCESS';
export const GET_USER_SONGS_FAIL = 'GET_USER_SONGS_FAIL';
export const GET_SONG_SUCCESS = 'GET_SONG_SUCCESS';
export const GET_SONG_FAIL = 'GET_SONG_FAIL';


// Tiers
export const GET_TIERS_SUCCESS = 'GET_TIERS_SUCCESS';
export const GET_TIERS_FAIL = 'GET_TIERS_FAIL';
export const GET_TIER_SUCCESS = 'GET_TIER_SUCCESS';
export const GET_TIER_FAIL = 'GET_TIER_FAIL';
export const GET_MYFOLLOWS_SUCCESS = 'GET_MYFOLLOWS_SUCCESS';
export const GET_MYFOLLOWS_FAIL = 'GET_MYFOLLOWS_FAIL';
export const GET_MYFANS_SUCCESS = 'GET_MYFANS_SUCCESS';
export const GET_MYFANS_FAIL = 'GET_MYFANS_FAIL';
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS';
export const GET_SUBSCRIPTION_FAIL = 'GET_SUBSCRIPTION_FAIL';


// Videos
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAIL = 'GET_VIDEOS_FAIL';
export const GET_VIDEOS_LIBRARY_SUCCESS = 'GET_VIDEOS_LIBRARY_SUCCESS';
export const GET_VIDEOS_LIBRARY_FAIL = 'GET_VIDEOS_LIBRARY_FAIL';
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';
export const GET_VIDEO_FAIL = 'GET_VIDEO_FAIL';
export const GET_MY_VIDEOS_SUCCESS = 'GET_MY_VIDEOS_SUCCESS';
export const GET_MY_VIDEOS_FAIL = 'GET_MY_VIDEOS_FAIL';
export const GET_USER_VIDEOS_SUCCESS = 'GET_USER_VIDEOS_SUCCESS';
export const GET_USER_VIDEOS_FAIL = 'GET_USER_VIDEOS_FAIL';
export const GET_VIDEOS_BY_ARRIVAL_SUCCESS = 'GET_VIDEOS_BY_ARRIVAL_SUCCESS';
export const GET_VIDEOS_BY_ARRIVAL_FAIL = 'GET_VIDEOS_BY_ARRIVAL_FAIL';
export const GET_VIDEOS_BY_SOLD_SUCCESS = 'GET_VIDEOS_BY_SOLD_SUCCESS';
export const GET_VIDEOS_BY_SOLD_FAIL = 'GET_VIDEOS_BY_SOLD_FAIL';
export const GET_VIDEOS_BY_RATING_SUCCESS = 'GET_VIDEOS_BY_RATING_SUCCESS';
export const GET_VIDEOS_BY_RATING_FAIL = 'GET_VIDEOS_BY_RATING_FAIL';
export const GET_VIDEOS_BY_VIEWS_SUCCESS = 'GET_VIDEOS_BY_VIEWS_SUCCESS';
export const GET_VIDEOS_BY_VIEWS_FAIL = 'GET_VIDEOS_BY_VIEWS_FAIL';
export const SEARCH_VIDEOS_SUCCESS = 'SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAIL = 'SEARCH_VIDEOS_FAIL';
export const RELATED_VIDEOS_SUCCESS = 'RELATED_VIDEOS_SUCCESS';
export const RELATED_VIDEOS_FAIL = 'RELATED_VIDEOS_FAIL';
export const FILTER_VIDEOS_SUCCESS = 'FILTER_VIDEOS_SUCCESS';
export const FILTER_VIDEOS_FAIL = 'FILTER_VIDEOS_FAIL';


export const GET_FOLLOWING_LIST_SUCCESS = 'GET_FOLLOWING_LIST_SUCCESS';
export const GET_FOLLOWING_LIST_FAIL = 'GET_FOLLOWING_LIST_FAIL';
export const GET_FOLLOWERS_LIST_SUCCESS = 'GET_FOLLOWERS_LIST_SUCCESS';
export const GET_FOLLOWERS_LIST_FAIL = 'GET_FOLLOWERS_LIST_FAIL';


export const GET_CAN_MESSAGE_LIST_SUCCESS = 'GET_CAN_MESSAGE_LIST_SUCCESS';
export const GET_CAN_MESSAGE_LIST_FAIL = 'GET_CAN_MESSAGE_LIST_FAIL';
export const GET_DIRECTS_SUCCESS = 'GET_DIRECTS_SUCCESS';
export const GET_DIRECTS_FAIL = 'GET_DIRECTS_FAIL';
export const GET_INBOX_SUCCESS = 'GET_INBOX_SUCCESS';
export const GET_INBOX_FAIL = 'GET_INBOX_FAIL';


export const GET_USERS_BY_EARNINGS_SUCCESS = 'GET_USERS_BY_EARNINGS_SUCCESS';
export const GET_USERS_BY_EARNINGS_FAIL = 'GET_USERS_BY_EARNINGS_FAIL';

export const GET_USERS_BY_SALES_SUCCESS = 'GET_USERS_BY_SALES_SUCCESS';
export const GET_USERS_BY_SALES_FAIL = 'GET_USERS_BY_SALES_FAIL';

export const GET_USERS_BY_SPENT_SUCCESS = 'GET_USERS_BY_SPENT_SUCCESS';
export const GET_USERS_BY_SPENT_FAIL = 'GET_USERS_BY_SPENT_FAIL';


export const LOAD_WEB3_SUCCESS = 'LOAD_WEB3_SUCCESS';
export const LOAD_WEB3_FAIL = 'LOAD_WEB3_FAIL';
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = 'LOAD_BLOCKCHAIN_DATA_SUCCESS';
export const LOAD_BLOCKCHAIN_DATA_FAIL = 'LOAD_BLOCKCHAIN_DATA_FAIL';

export const LOAD_ETHSWAP_SUCCESS = 'LOAD_ETHSWAP_SUCCESS';
export const LOAD_ETHSWAP_FAIL = 'LOAD_ETHSWAP_FAIL';
export const LOAD_ETHSWAP_BUY_SUCCESS = 'LOAD_ETHSWAP_BUY_SUCCESS';
export const LOAD_ETHSWAP_BUY_FAIL = 'LOAD_ETHSWAP_BUY_FAIL';

export const LOAD_URIDIUM_SUCCESS = 'LOAD_URIDIUM_SUCCESS';
export const LOAD_URIDIUM_FAIL = 'LOAD_URIDIUM_FAIL';
export const LOAD_URIDIUM_BALANCE_SUCCESS = 'LOAD_URIDIUM_BALANCE_SUCCESS';
export const LOAD_URIDIUM_BALANCE_FAIL = 'LOAD_URIDIUM_BALANCE_FAIL';

export const LOAD_CREDITS_SUCCESS = 'LOAD_CREDITS_SUCCESS';
export const LOAD_CREDITS_FAIL = 'LOAD_CREDITS_FAIL';
export const LOAD_CREDITS_BALANCE_SUCCESS = 'LOAD_CREDITS_BALANCE_SUCCESS';
export const LOAD_CREDITS_BALANCE_FAIL = 'LOAD_CREDITS_BALANCE_FAIL';

export const LOAD_ETHEREUM_SUCCESS = 'LOAD_ETHEREUM_SUCCESS';
export const LOAD_ETHEREUM_FAIL = 'LOAD_ETHEREUM_FAIL';
export const LOAD_ETHEREUM_BALANCE_SUCCESS = 'LOAD_ETHEREUM_BALANCE_SUCCESS';
export const LOAD_ETHEREUM_BALANCE_FAIL = 'LOAD_ETHEREUM_BALANCE_FAIL';

export const LOAD_TETHER_SUCCESS = 'LOAD_TETHER_SUCCESS';
export const LOAD_TETHER_FAIL = 'LOAD_TETHER_FAIL';
export const LOAD_TETHER_BALANCE_SUCCESS = 'LOAD_TETHER_BALANCE_SUCCESS';
export const LOAD_TETHER_BALANCE_FAIL = 'LOAD_TETHER_BALANCE_FAIL';

export const LOAD_BANK_SUCCESS = 'LOAD_BANK_SUCCESS';
export const LOAD_BANK_FAIL = 'LOAD_BANK_FAIL';
export const LOAD_BANK_BALANCE_SUCCESS = 'LOAD_BANK_BALANCE_SUCCESS';
export const LOAD_BANK_BALANCE_FAIL = 'LOAD_BANK_BALANCE_FAIL';

export const LOAD_NETWORK_SUCCESS = 'LOAD_NETWORK_SUCCESS';
export const LOAD_NETWORK_FAIL = 'LOAD_NETWORK_FAIL';


export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS';
export const SET_LOADING_FAIL = 'SET_LOADING_FAIL';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';
export const GET_MY_USER_DETAILS_SUCCESS = 'GET_MY_USER_DETAILS_SUCCESS';
export const GET_MY_USER_DETAILS_FAIL = 'GET_MY_USER_DETAILS_FAIL';
